## Project F: Life on Screen - iCEBreaker Makefile
## (C)2021 Will Green, open source hardware released under the MIT License
## Learn more at https://projectf.io

# configuration
SHELL = /bin/sh
FPGA_PKG = sg48
FPGA_TYPE = up5k
PCF = icebreaker.pcf

# included modules
PATH_CM  = ../../common
ADD_SRC  = ${PATH_CM}/rom_async.sv ${PATH_CM}/xd.sv
ADD_SRC += ${PATH_CM}/ice40/bram_sdp.sv ${PATH_CM}/ice40/clock_gen_480p.sv
ADD_SRC += ../display_timings_480p.sv ../framebuffer.sv ../linebuffer.sv
ADD_SRC += ../life.sv

top_life: top_life.rpt top_life.bin

%.json: %.sv
	yosys -ql $(subst .json,,$@)-yosys.log -p 'synth_ice40 -top $(subst .json,,$@) -json $@' $< $(ADD_SRC)

%.asc: %.json
	nextpnr-ice40 --${FPGA_TYPE} --package ${FPGA_PKG} --json $< --pcf ${PCF} --asc $@

%.rpt: %.asc
	icetime -d ${FPGA_TYPE} -mtr $@ $<

%.bin: %.asc
	icepack $< $@

clean:
	rm -f top*.json top*.asc top*.rpt top*.bin top*yosys.log

all: top_life

.PHONY: all clean
